"""
Week 06 INDIVIDUAL ASSIGNMENT -- Patch Compliance Audit
ITIA 1510 Cybersecurity Automation

Tests for the functions in patch_audit.py. Do not edit this file.

Run it from the folder that holds patch_audit.py:

    python -m unittest test_patch_audit -v

Run it before you change anything: 30 of the 44 tests fail. The other 14 pass
by accident, because a placeholder happens to return the right answer for that
one case, so a green test is only worth something once you have written the
function. Work through the TODOs and the rest turn green a few at a time.

The report TODOs, 13 through 20, are not tested here. Check those against the
table in the assignment.
"""

import unittest

try:
    import patch_audit as pa
except ModuleNotFoundError:
    # the instructor copy of the program keeps its week06_ name
    import week06_individual_patch_audit as pa


class TestPatchLimit(unittest.TestCase):
    """TODO 1"""

    def test_criticality_3_gets_14_days(self):
        self.assertEqual(pa.patch_limit(3), 14)

    def test_criticality_2_gets_30_days(self):
        self.assertEqual(pa.patch_limit(2), 30)

    def test_criticality_1_gets_60_days(self):
        self.assertEqual(pa.patch_limit(1), 60)


class TestIsValidRecord(unittest.TestCase):
    """TODO 2"""

    def test_normal_record_is_valid(self):
        self.assertTrue(pa.is_valid_record(9, 3))

    def test_zero_days_is_valid(self):
        self.assertTrue(pa.is_valid_record(0, 1))

    def test_negative_days_is_invalid(self):
        self.assertFalse(pa.is_valid_record(-1, 1))

    def test_criticality_0_is_invalid(self):
        self.assertFalse(pa.is_valid_record(20, 0))

    def test_negative_days_with_bad_criticality_is_invalid(self):
        self.assertFalse(pa.is_valid_record(-5, 9))


class TestPatchStatus(unittest.TestCase):
    """TODO 3"""

    def test_inside_the_limit_is_compliant(self):
        self.assertEqual(pa.patch_status("dc-01", 9, 3, []), "COMPLIANT")

    def test_exactly_on_the_limit_is_compliant(self):
        self.assertEqual(pa.patch_status("mail-01", 30, 2, []), "COMPLIANT")

    def test_one_day_past_the_limit_is_overdue(self):
        self.assertEqual(pa.patch_status("file-01", 61, 1, []), "OVERDUE")

    def test_exactly_twice_the_limit_is_overdue(self):
        self.assertEqual(pa.patch_status("web-02", 60, 2, []), "OVERDUE")

    def test_past_twice_the_limit_is_critical(self):
        self.assertEqual(pa.patch_status("db-01", 95, 3, []), "CRITICAL")

    def test_bad_criticality_is_invalid(self):
        self.assertEqual(pa.patch_status("vpn-01", 20, 0, []), "INVALID")

    def test_negative_days_is_invalid(self):
        self.assertEqual(pa.patch_status("print-01", -1, 1, []), "INVALID")

    def test_exemption_beats_a_broken_record(self):
        # lab-sandbox-02 has both. The exception list wins.
        self.assertEqual(
            pa.patch_status("lab-sandbox-02", -1, 1, ["lab-sandbox-02"]), "EXEMPT")

    def test_exemption_beats_being_overdue(self):
        self.assertEqual(
            pa.patch_status("lab-sandbox-01", 400, 1, ["lab-sandbox-01"]), "EXEMPT")


class TestDaysOverdue(unittest.TestCase):
    """TODO 4"""

    def test_overdue_host(self):
        self.assertEqual(pa.days_overdue(95, 3), 81)

    def test_compliant_host_is_zero_not_negative(self):
        self.assertEqual(pa.days_overdue(9, 3), 0)

    def test_exactly_on_the_limit_is_zero(self):
        self.assertEqual(pa.days_overdue(60, 1), 0)


class TestOverdueBar(unittest.TestCase):
    """TODO 5"""

    def test_not_overdue_is_empty(self):
        self.assertEqual(pa.overdue_bar(0), "")

    def test_one_day_still_gets_one_mark(self):
        self.assertEqual(pa.overdue_bar(1), "#")

    def test_nine_days_still_gets_one_mark(self):
        self.assertEqual(pa.overdue_bar(9), "#")

    def test_eighty_one_days(self):
        self.assertEqual(pa.overdue_bar(81), "########")

    def test_bar_never_passes_ten_marks(self):
        self.assertEqual(pa.overdue_bar(5000), "##########")


class TestWillLapse(unittest.TestCase):
    """TODO 6"""

    def test_compliant_host_that_runs_out(self):
        self.assertTrue(pa.will_lapse(9, 3, 10))

    def test_compliant_host_with_room_to_spare(self):
        self.assertFalse(pa.will_lapse(9, 3, 2))

    def test_host_already_past_its_limit_does_not_lapse_again(self):
        self.assertFalse(pa.will_lapse(95, 3, 10))


class TestBuildStatuses(unittest.TestCase):
    """TODO 7"""

    def test_one_status_per_host(self):
        statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(len(statuses), len(pa.HOSTS))

    def test_the_whole_inventory(self):
        statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(statuses, [
            "COMPLIANT", "CRITICAL", "COMPLIANT", "OVERDUE", "CRITICAL",
            "COMPLIANT", "OVERDUE", "CRITICAL", "COMPLIANT", "EXEMPT",
            "EXEMPT", "INVALID", "INVALID",
        ])


class TestCountStatus(unittest.TestCase):
    """TODO 8"""

    def setUp(self):
        self.statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)

    def test_counts(self):
        self.assertEqual(pa.count_status(self.statuses, "COMPLIANT"), 4)
        self.assertEqual(pa.count_status(self.statuses, "OVERDUE"), 2)
        self.assertEqual(pa.count_status(self.statuses, "CRITICAL"), 3)
        self.assertEqual(pa.count_status(self.statuses, "EXEMPT"), 2)
        self.assertEqual(pa.count_status(self.statuses, "INVALID"), 2)

    def test_a_status_nobody_has_counts_zero(self):
        self.assertEqual(pa.count_status(self.statuses, "PENDING"), 0)


class TestHostsWithStatus(unittest.TestCase):
    """TODO 9"""

    def setUp(self):
        self.statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)

    def test_critical_hosts_in_inventory_order(self):
        self.assertEqual(
            pa.hosts_with_status(pa.HOSTS, self.statuses, "CRITICAL"),
            ["dc-02", "db-01", "hr-laptop-07"])

    def test_overdue_hosts_in_inventory_order(self):
        self.assertEqual(
            pa.hosts_with_status(pa.HOSTS, self.statuses, "OVERDUE"),
            ["web-02", "file-01"])

    def test_a_status_nobody_has_gives_an_empty_list(self):
        self.assertEqual(pa.hosts_with_status(pa.HOSTS, self.statuses, "PENDING"), [])


class TestWorstHost(unittest.TestCase):
    """TODO 10"""

    def test_most_days_overdue_is_not_most_days_since_patch(self):
        statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        worst = pa.worst_host(pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, statuses)
        self.assertEqual(pa.HOSTS[worst], "db-01")

    def test_returns_minus_one_when_nothing_is_overdue(self):
        hosts = ["a", "b"]
        days = [1, 2]
        crits = [1, 1]
        statuses = ["COMPLIANT", "COMPLIANT"]
        self.assertEqual(pa.worst_host(hosts, days, crits, statuses), -1)


class TestRemoveExempt(unittest.TestCase):
    """TODO 11, the first defect"""

    def test_both_exempt_hosts_are_removed(self):
        self.assertEqual(len(pa.remove_exempt(pa.HOSTS, pa.EXEMPT)), 11)

    def test_neither_sandbox_survives(self):
        remaining = pa.remove_exempt(pa.HOSTS, pa.EXEMPT)
        self.assertNotIn("lab-sandbox-01", remaining)
        self.assertNotIn("lab-sandbox-02", remaining)

    def test_adjacent_exempt_hosts_are_both_removed(self):
        # The defect skips the second of two neighbours.
        self.assertEqual(pa.remove_exempt(["a", "x", "y", "b"], ["x", "y"]), ["a", "b"])

    def test_the_original_list_is_not_changed(self):
        before = list(pa.HOSTS)
        pa.remove_exempt(pa.HOSTS, pa.EXEMPT)
        self.assertEqual(pa.HOSTS, before)


class TestAverageDays(unittest.TestCase):
    """TODO 12, the second defect"""

    def test_average_of_the_judged_hosts(self):
        statuses = pa.build_statuses(
            pa.HOSTS, pa.DAYS_SINCE_PATCH, pa.CRITICALITY, pa.EXEMPT)
        self.assertEqual(pa.average_days(pa.DAYS_SINCE_PATCH, statuses), 52.3)

    def test_the_first_host_is_counted(self):
        # Skipping position 0 is half of the defect.
        self.assertEqual(pa.average_days([10, 20], ["COMPLIANT", "COMPLIANT"]), 15.0)

    def test_exempt_and_invalid_are_left_out_of_both_halves(self):
        # Dividing by the full length is the other half.
        self.assertEqual(
            pa.average_days([10, 20, 999, 999], ["COMPLIANT", "COMPLIANT", "EXEMPT", "INVALID"]),
            15.0)


if __name__ == "__main__":
    unittest.main(verbosity=2)